### ISSUE TITLE
Welcome content for 8.0 documentation

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1090]
## Tasks

- [x] Create repositories to host in different places the content, the sources and the theme
- [x] Modify deploy workflow to rely on the three repositories
- [x] Rebase current PRs for `docs` to target `1.7.x`
- [x] Remove the `master` branch (Warning: not to be done before all open PRs have been rebased, or else they will be closed!)
- [x] Create the `8.x` branch in `docs`
- [x] Add it as a submodule in the `devdocs-site` and put it in the `8` directory
- [x] https://github.com/PrestaShop/docs/issues/1105

<hr>

## Developer need

Users need to be able to browse either the 1.7 documentation or the 8.0 documentation.

Also it would be great if user, when visiting a docs page, can choose "the 8.0 page" or "the 1.7 page" about the same topic (see how Symfony provides this feature https://symfony.com/doc/current/doctrine.html)

## Implementation insights

This raises the question: how are we going to store the documentation for 1.7 and 8.0 ?
- same repository, 2 folders, but 1 file per version, 2 files per topic ?
- same repository, each page has a 1.7 part and a 8.0 part so 1 file per topic ?
- same repository, two branches
- two repositories, merged together as git submodules?

**Comment by matks** [comment]
Assigned to @eternoendless at least for the implementation details that have to be decided

**Comment by eternoendless** [comment]
After discussing it with the teams, we're most likely going to do it like this:

- The `docs` repository will be updated so that it only contains the content of the `src/content/1.7/` directory.
- The default branch will be called `doc1.7`
- We will create a new branch called `doc8`
- A new repository called `devdocs-site` will contain the Hugo configuration, then import the two branches from `docs` repository as submodules, into ``src/content/1.7/` and `src/content/8/`

**Comment by matks** [comment]
Work in progress
- https://github.com/PrestaShop/docs/pull/1095
- https://github.com/PrestaShop/ps-docs-theme
- https://github.com/PrestaShop/devdocs-site

**Comment by eternoendless** [comment]
The repositories and deployment have been put in place. Next steps:

- [x] Rebase current PRs for `docs` to target `1.7.x`
- [x] Remove the `master` branch (Warning: not to be done before all open PRs have been rebased, or else they will be closed!)
- [x] Create the `8.x` branch in `docs`
- [x] Add it as a submodule in the `devdocs-site` and put it in the `8` directory

**Comment by matks** [comment]
> The repositories and deployment have been put in place. Next steps:
> 
> * [ ]  Rebase current PRs for `docs` to target `1.7.x`
> * [ ]  Remove the `master` branch (Warning: not to be done before all open PRs have been rebased, or else they will be closed!)
> * [ ]  Create the `8.x` branch in `docs`
> * [ ]  Add it as a submodule in the `devdocs-site` and put it in the `8` directory

List completed and copied above

**Comment by matks** [comment]
All PRs on docs have been changed to target the 1.7.x branch with an information message.

There is only one PR that targets `master` now: this one from @Progi1984 https://github.com/PrestaShop/docs/pull/1077 

This PR needs to target `8.x` branch after it has been created.

**Comment by matks** [comment]
It's live ! https://devdocs.prestashop.com/
