### ISSUE TITLE
[Roadmap] Improve Testing section

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1319]
Testing section should present clearly

- [ ] How to run PrestaShop test suites, including the nightly suite 🟠
- [ ] How these test suites are structured, the inner behavior and logic 🟠
- [ ] How to contribute to the project by adding tests 🔴 
- [ ] How to write your own tests for your shop 🟠
- [ ] How to write your own tests for your module 🟠

One good example of "How to contribute to the project by adding tests" can be found at Sylius https://docs.sylius.com/en/latest/bdd/index.html

🟠 = can be improved
🔴 = does not exist
