### ISSUE TITLE
[Roadmap] Improve Modules section

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1320]
### In general

Modules shat section should always take care of presenting 2 different use cases:

- I build something in my module that is loaded and rendered outside of PrestaShop (like a new BO page)
- I decorate / extend an existing page of PrestaShop, then some constraints apply

We should provide clear pages about “OK, you want to customize BO page Z ? add a block there and a field in this form? Here is the path you should follow, what to look for…”

### Roadmap

- [x] Introduction ✅
- [x] Getting started ✅
#### Extension concepts
- [ ] JS events on FO 🔴
- [ ] Routing 🔴
- [ ] Controllers
  - [ ] Front Controllers  🟠
  - [ ] Admin Symfony Controllers 🟠
  - [ ] Admin Legacy Controllers  🔴
- [ ] Hooks 🟠
… 
- [ ] Payment modules 🟠
- [ ] Carrier modules 🟠
- [x] Testing ✅
- [x] Core changes ✅
- [x] Selling your modules ➡️ removed in doc 8.x
- [ ] Sample modules 🟠

### Related questions

- https://github.com/PrestaShop/docs/issues/1204

✅ = quite complete (although can always be improved)
🟠 = can be improved
🔴 = does not exist
