### ISSUE TITLE
[Roadmap] Improve Core reference section

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1324]
- [x] **Coding standards** ✅
- [x] **Naming conventions** ✅
- [ ] Architecture > Introduction 🟠
- [ ] Architecture > File structure 🟠
- [ ] Architecture > Legacy 🟠
- [ ] Architecture > Modern 🟠
- [ ] Architecture > Migration guide 🟠
- [ ] Architecture > Domain-driven architecture 🟠
- [ ] Architecture > Cache ➡️
- [x] **Database** ✅
- [ ] **Orders lifecycle** 🟠 
_(nice example https://docs.sylius.com/en/latest/book/index.html#carts-orders)_
- [ ] **Products workflow / structure / lifecycle** 🔴 
  - [ ] https://github.com/PrestaShop/docs/issues/1085
_(nice example https://docs.sylius.com/en/latest/book/index.html#products)_
- [x] Page Reference > BO pages > Order ✅
- [ ] Page Reference > BO pages > Product 🟠
- [ ] Page Reference 🔴  _(we should explain some more important BO pages like dashboard)_
- [ ] Components section ==>  https://github.com/PrestaShop/docs/issues/1325
- [ ] **Internationalization > Translation** 🟠  _(content is quite complete but structure is complex)_
  - https://github.com/PrestaShop/docs/issues/1316
- [x] **Internationalization > Localization packs** ✅
  - [ ] https://github.com/PrestaShop/docs/issues/1068
- [x] **Internationalization > RTL Languages** ✅
- [x] **How to compile assets** ➡️
- [x] **Sending emails** ➡️
- [x] **UI Kit** ✅
- [x] **Native modules** ✅
- [x] **Upgrade module** ✅
- [ ] **Multistore** 🟠 _(see nice example https://www.drupal.org/docs/multisite-drupal)_
- [ ] **Security** 🔴

➡️= must move or must be removed
✅ = quite complete (although can always be improved)
🟠 = can be improved
🔴 = does not exist
