### ISSUE TITLE
Improve Core reference > Components section

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1325]
- [x] BO sidebar ✅
- [x] Configuration storage ✅
- [ ] Controllers 🔴 _(see nice example https://developers.shopware.com/developers-guide/controller/)_
- [ ] Context 🟠
- [ ] Locales and currencies 🔴
- [ ] Database 🟠
  - [ ] https://github.com/PrestaShop/docs/issues/1141
- [ ] Global JS components 🟠
- [ ] Helper classes 🟠 _(need to be updated and Symfony alternatives documented)_
  - [x] HelperForm ✅
  - [x] HelperList ✅
  - [x] HelperOptions ✅
- [ ] Router and dispatcher ✅
- [ ] Smarty Extensions 🟠
- [x] Console ✅
- [x] Faceted search ✅
- [ ] Form 🟠
- [ ] Grid 🟠  _(needs to be updated)_
- [ ] Hook 🟠
- [ ] Classes like DataProvider, Repositories … 🔴  _(see nice example https://devdocs.magento.com/guides/v2.4/extension-dev-guide/searching-with-repositories.html)_
- [x] Import ✅
- [x] Mail templates ✅
- [ ] Images 🔴 https://github.com/PrestaShop/docs/issues/1084
- [ ] Position updater ➡️ should move into Grid section
- [ ] TinyMCE ➡️ should move into JS components section
- [ ] Users 🟠  _(see below)_
- [ ] All JS components (like TinyMCE) 🔴 a section for all JS
- [ ] Webservice 🔴 should be a link to top section
- [ ] The Front-office 🔴 document the Cart, the checkout process…
- [ ]  Prices 🔴 see https://devdocs.magento.com/guides/v2.4/extension-dev-guide/price-adjustments.html

For Users: we need to document how FO users login, how BO users login, document the user properties and capabilities, customer addresses, customer carts... …

FO User is a Customer 🔴  -> see nice example https://docs.sylius.com/en/latest/book/index.html#customers

➡️= must move or must be removed
✅ = quite complete (although can always be improved)
🟠 = can be improved
🔴 = does not exist
