### ISSUE TITLE
Document PrestaShop 8.0.0 on devdocs.prestashop.com

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1603]
Following the development of PrestaShop 8 we need to document it to be able to release PrestaShop 8.0.0 RC.

**This ticket is a meta-ticket that lists all components we need to document**.

Each of the item below must be documented by the developer who built it. This is not a ticket anybody can do.

### Document software changes, BC breaks and new hooks
- [x] https://github.com/PrestaShop/docs/issues/1447
- [x] https://github.com/PrestaShop/docs/issues/1449

### Document PrestaShop 8.0 main new features
- [x] https://github.com/PrestaShop/docs/issues/1445
- [x] https://github.com/PrestaShop/docs/issues/1436
- [x] https://github.com/PrestaShop/docs/issues/1448
- [ ] https://github.com/PrestaShop/docs/issues/1340
- [x] https://github.com/PrestaShop/docs/issues/1331
- [ ] Document new session management https://github.com/PrestaShop/PrestaShop/pull/21120

### Document new developer capabilities
- [x] Document https://github.com/PrestaShop/PrestaShop/pull/27952
- [ ] Document https://github.com/PrestaShop/PrestaShop/pull/23413

### Make sure our example modules are compatible with PrestaShop 8.0
https://github.com/PrestaShop/example-modules

**Comment by kpodemski** [comment]
@matks 

FYI: I'll take on https://github.com/PrestaShop/PrestaShop/pulls?page=7&q=is%3Apr+is%3Amerged+label%3A%22Needs+documentation%22+milestone%3A8.0.0

👍

**Comment by matks** [comment]
@kpodemski Can I close this issue?

**Comment by kpodemski** [comment]
@matks 

I think some topics could be discussed with @thomasnares 

@thomasnares do you think it's doable to document:
PrestaShop/PrestaShop#1447
PrestaShop/PrestaShop#1436
PrestaShop/PrestaShop#1448

?

@matks I think the product page has to wait, I spoke with @MatShir, and it's probably better to wait for the feature freeze and then tackle this subject for the 8.1

`DKIM`, not sure if it's needed, core handles that internally. Unless we want to have a section of what DKIM is?

`Session management` I'd treat it as a nice-to-have
`Module manager` is a very interesting topic because it could allow developers to inject their marketplace just like `ps_mbo` does. It would be great to have it documented based on the `ps_distributionapiclient` but it's probably a lot of work.

**Comment by thomasnares** [comment]
@kpodemski yes i'm adding them to my todo 👍

**Comment by matks** [comment]
I just found a `[To be completed]` in https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/#new-product-page 😉

**Comment by thomasnares** [comment]
😬, made a PR for this:  https://github.com/PrestaShop/docs/pull/1657
