### ISSUE TITLE
[EPIC] Write and adapt developer documentation for v9

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/docs#1846]
We need to create the 9.x branch for the developer documentation, and populate it with the v9 added and changed content:

- [x] Create a “Notable changes” section for 9.0, similar to https://devdocs.prestashop-project.org/8/modules/core-updates/8.1/
- [x] Inside that section, document the framework & dependency changes between PS 8 and PS 9, especially Symfony, and how module developers need to adapt their code if they used these
  - [x] https://github.com/PrestaShop/docs/issues/1658
  - [x] https://github.com/PrestaShop/docs/issues/1653
  - [x] document all [BC Breaks](https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+is%3Amerged+label%3A%22BC+break%22)
  - [x] Update the doc regarding the refacto of controllers

API documentation
- [x] Create the builder documentation for the new Backoffice API: document how it is built (to help future developers who need to understand it), what endpoints are available in v9 build => https://github.com/PrestaShop/docs/pull/1860
- [x] Create the user documentation for the new Backoffice API: document how to use it => https://build.prestashop-project.org/news/2024/meet-prestashop9-api/

Symfony layout
- [x] Create the builder documentation for the Symfony Layout: how it is built, major changes between legacy and Symfony layout, how module developers should adapt their code for v9 => https://devdocs.prestashop-project.org/9/modules/core-updates/9.0/#symfony-layout

To do: better describe each item, how to organize it, how to integrate it into devdocs

**Comment by kpodemski** [comment]
Requires a better understanding of the impact:

1. https://github.com/PrestaShop/PrestaShop/pull/33775
2. https://github.com/PrestaShop/PrestaShop/pull/33223 - before and after recommendations + improvements for the https://devdocs.prestashop-project.org/9/development/components/context/
3. Changes to translations may require even more details, especially regarding the usage of a new translation method, possibly adding a way to easily export .xlf for a module, etc. (https://github.com/PrestaShop/PrestaShop/pull/30415, https://github.com/PrestaShop/PrestaShop/pull/31900)
4. Add to docs about ObjectModel: https://github.com/PrestaShop/PrestaShop/pull/33624

To be continued.

**Comment by kpodemski** [comment]
Hooks to document:

1. `actionBackOfficeLoginForm`
2. `actionEmployeeRequestPasswordResetForm`
3. `actionPresentCategory`
4. `actionPresentSupplier`
5. `actionPresentManufacturer`
6. `actionPresentStore`

**Comment by kpodemski** [comment]
Remember about adding Carriers page to the list of migrated pages (behind the feature flag).

**Comment by kpodemski** [comment]
~~[This page](https://devdocs.prestashop-project.org/9/modules/creation/external-services/) has to be adjusted because it mentions Guzzle.~~
